version: '3.9'

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app  # Para desarrollo, sincroniza los cambios locales
    environment:
      - ENVIRONMENT=development
